baseurl: "Dummy-HR/"

collections:
    - 01_Vorwort
    - 02_Grundlagen
    - 03_Module
    - 04_Impressum 

collections:
    chapters:
        output: true
        permalink: /chapters/:path/

defaults:
  - scope:
        path: ""
        type: chapters
    values:
        layout: kapitel
